added a new "check-npm-package-metadata" validation job

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -67,10 +67,26 @@ jobs:
           failed=0
           npm view ${{ needs.parse-issue-form-body.outputs.npm-package }} name || failed=1
           if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: A link to the NPM package is incorrect or the NPM package doesn't exist."; exit 1; fi;
+  check-npm-package-metadata:
+    name: Check NPM package metadata
+    runs-on: ubuntu-latest
+    needs: [parse-issue-form-body, check-npm-link]
+    outputs:
+      error: ${{ steps.check-npm-package-metadata.outputs.error }}
+    steps:
+      - name: Check NPM package metadata
+        id: check-npm-package-metadata
+        run: |
+          failed=0
+          npm install @adobe/aio-lib-template-validation || failed=1
+          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: Failed installing @adobe/aio-lib-template-validation"; exit 1; fi;
+          npx tv run-checks ${{ needs.parse-issue-form-body.outputs.npm-link }} 2>&1 > output.log || failed=1
+          cat output.log
+          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: `cat output.log`"; exit 1; fi;
   check-npm-package:
     name: Validate template
     runs-on: ubuntu-latest
-    needs: [parse-issue-form-body, check-npm-link, check-github-link]
+    needs: [parse-issue-form-body, check-npm-package-metadata, check-github-link]
     if: ${{ needs.check-github-link.outputs.error == '' }}
     strategy:
       matrix:
@@ -133,7 +149,7 @@ jobs:
   fail-validation-comment:
     name: Validation failed
     runs-on: ubuntu-latest
-    needs: [check-npm-package, check-github-link, check-npm-link]
+    needs: [check-npm-package, check-github-link, check-npm-link, check-npm-package-metadata]
     if: ${{ always() && (needs.check-npm-package.result != 'success' || needs.check-github-link.outputs.error != '') }}
     steps:
       - uses: ben-z/actions-comment-on-issue@1.0.2
@@ -142,5 +158,6 @@ jobs:
             :x: Template validation failed.
             ${{ needs.check-github-link.outputs.error }}
             ${{ needs.check-npm-link.outputs.error }}
+            ${{ needs.check-npm-package-metadata.outputs.error }}
             ${{ needs.check-npm-package.outputs.error }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
