git checkout `npm view ${{ needs.parse-issue-form-body.outputs.npm-package }} gitHead`

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -87,15 +87,23 @@ jobs:
         id: check-installation-and-tests
         run: |
           failed=0
-          echo '[COMMAND] mkdir "npm-package"; cd "npm-package"'
-          mkdir "npm-package"; cd "npm-package"
+          echo '[COMMAND] mkdir "npm-package" && cd "npm-package"'
+          mkdir "npm-package" && cd "npm-package"
           echo '[COMMAND] npm init --yes'
           npm init --yes
           echo '[COMMAND] npm install ${{ needs.parse-issue-form-body.outputs.npm-package }}'
           npm install ${{ needs.parse-issue-form-body.outputs.npm-package }} || failed=1
           if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: A package installation failed."; exit 1; fi;
-          echo '[COMMAND] cp -R "./node_modules/${{ needs.parse-issue-form-body.outputs.npm-package }}" "installed-npm-package-src"; cd "installed-npm-package-src"'
-          cp -R "./node_modules/${{ needs.parse-issue-form-body.outputs.npm-package }}" "installed-npm-package-src"; cd "installed-npm-package-src"
+          echo '[COMMAND] cd .. && mkdir "npm-package-src"'
+          cd .. && mkdir "npm-package-src"
+          echo '[COMMAND] git clone ${{ needs.parse-issue-form-body.outputs.github-link }} "npm-package-src"'
+          git clone ${{ needs.parse-issue-form-body.outputs.github-link }} "npm-package-src" || failed=1
+          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: Failed cloning the GitHub repository."; exit 1; fi;
+          echo '[COMMAND] cd "npm-package-src"'
+          cd "npm-package-src"
+          echo '[COMMAND] git checkout `npm view ${{ needs.parse-issue-form-body.outputs.npm-package }} gitHead`'
+          git checkout `npm view ${{ needs.parse-issue-form-body.outputs.npm-package }} gitHead` || failed=1
+          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: Failed switching to the GitHub commit hash."; exit 1; fi;
           echo '[COMMAND] npm install --legacy-peer-deps'
           npm install --legacy-peer-deps || failed=1
           if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: A package's dependencies installation failed."; exit 1; fi;
