output=$(cat output.log)

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -82,7 +82,8 @@ jobs:
           if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: Failed installing @adobe/aio-lib-template-validation"; exit 1; fi;
           npx tv run-checks ${{ needs.parse-issue-form-body.outputs.npm-link }} 2>&1 > output.log || failed=1
           cat output.log
-          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: `cat output.log`"; exit 1; fi;
+          output=$(cat output.log)
+          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: ${output}"; exit 1; fi;
   check-npm-package:
     name: Validate template
     runs-on: ubuntu-latest
